Update install

diff --git a/install b/install
--- a/install
+++ b/install
@@ -466,7 +466,12 @@ setup_drive() {
 create_zfs() {
 
     echo ">>> loading ZFS modules"
-    modprobe zfs || echo 'ERROR: ZFS modules are missing' && create_rootfs
+    modprobe zfs
+    echo ">>> checking ZFS modules"
+    if ! lsmod | grep -qi zfs; then
+       echo 'ERROR: ZFS modules are missing'
+       create_rootfs
+    fi
     echo ">>> creating ZFS pool"
     zpool create -f -o ashift=12 -o autotrim=on \
     -O recordsize=8192 -O compression=lz4 \
